import 'dart:convert';
import 'dart:io';

import 'package:allways_games/games/dot_dominoes/domain/domino_puzzle.dart';
import 'package:allways_games/games/dot_dominoes/domain/domino_solver.dart';
import 'package:flutter_test/flutter_test.dart';

/// Guards the committed asset.
///
/// The generator checks each puzzle as it writes it, but the file is what
/// ships, and it can be regenerated by a changed tool. This re-checks the
/// real bytes — including a uniqueness sample, which is the property the
/// whole game rests on.
void main() {
  final raw =
      File('assets/content/dot_dominoes/bank.json').readAsStringSync();
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final puzzles = (json['puzzles'] as List)
      .cast<Map<String, dynamic>>()
      .map(DominoPuzzle.fromJson)
      .toList();

  test('the bank holds years of puzzles', () {
    expect(puzzles.length, greaterThan(365));
  });

  test('every board is fully covered by its regions, exactly once', () {
    for (var p = 0; p < puzzles.length; p++) {
      final puzzle = puzzles[p];
      final counted = <int, int>{};
      for (final region in puzzle.regions) {
        expect(region.cells, isNotEmpty, reason: 'puzzle $p');
        for (final cell in region.cells) {
          expect(puzzle.present[cell], isTrue, reason: 'puzzle $p cell $cell');
          counted[cell] = (counted[cell] ?? 0) + 1;
        }
      }
      for (final cell in puzzle.cells) {
        expect(counted[cell], 1, reason: 'puzzle $p cell $cell');
      }
    }
  });

  test('the tray matches the board and never repeats a tile', () {
    for (var p = 0; p < puzzles.length; p++) {
      final puzzle = puzzles[p];
      expect(puzzle.cells.length, puzzle.tray.length * 2, reason: 'puzzle $p');
      expect(
        puzzle.tray.toSet().length,
        puzzle.tray.length,
        reason: 'puzzle $p repeats a domino',
      );
    }
  });

  test('every recorded solution really is a solution', () {
    for (var p = 0; p < puzzles.length; p++) {
      expect(
        DominoSolver.isValidSolution(puzzles[p], puzzles[p].solution),
        isTrue,
        reason: 'puzzle $p',
      );
    }
  });

  test('a sample of puzzles have exactly one solution', () {
    // Solving is the expensive check, so this samples rather than sweeps;
    // the generator already proved it for every puzzle as it wrote them.
    for (var p = 0; p < puzzles.length; p += 97) {
      expect(
        DominoSolver.countSolutions(puzzles[p]),
        1,
        reason: 'puzzle $p is not unique',
      );
    }
  });
}
