import 'dart:convert';
import 'dart:io';

import 'package:allways_games/games/crossword/domain/crossword_grid.dart';
import 'package:allways_games/games/crossword/domain/crossword_puzzle.dart';
import 'package:flutter_test/flutter_test.dart';

/// Guards the committed asset.
///
/// The generator checks each puzzle as it writes it, but the file is what
/// actually ships — and it can be regenerated by a changed tool, or edited
/// by hand. This re-checks the real bytes.
void main() {
  final raw = File('assets/content/crossword/bank.json').readAsStringSync();
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final puzzles = (json['puzzles'] as List)
      .cast<Map<String, dynamic>>()
      .map(CrosswordPuzzle.fromJson)
      .toList();

  test('the bank holds years of puzzles', () {
    expect(puzzles.length, greaterThan(365));
  });

  test('every grid agrees with its entries', () {
    for (var p = 0; p < puzzles.length; p++) {
      final puzzle = puzzles[p];
      expect(puzzle.solution.length, crosswordCellCount, reason: 'puzzle $p');
      expect(puzzle.blocked.length, crosswordCellCount, reason: 'puzzle $p');

      for (final entry in puzzle.entries) {
        expect(entry.answer.length, entry.cells.length, reason: 'puzzle $p');
        expect(
          entry.answer.length,
          greaterThanOrEqualTo(crosswordMinEntry),
          reason: 'puzzle $p ${entry.label}',
        );
        expect(entry.clue.trim(), isNotEmpty, reason: 'puzzle $p');
        for (var i = 0; i < entry.cells.length; i++) {
          expect(
            puzzle.solution[entry.cells[i]],
            entry.answer[i],
            reason: 'puzzle $p ${entry.label}',
          );
        }
      }
    }
  });

  test('blocked squares are blank and open squares are filled', () {
    for (var p = 0; p < puzzles.length; p++) {
      final puzzle = puzzles[p];
      for (var i = 0; i < crosswordCellCount; i++) {
        final letter = puzzle.solution[i].trim();
        if (puzzle.blocked[i]) {
          expect(letter, isEmpty, reason: 'puzzle $p cell $i');
        } else {
          expect(letter, isNotEmpty, reason: 'puzzle $p cell $i');
        }
      }
    }
  });

  test('no grid repeats a word', () {
    for (var p = 0; p < puzzles.length; p++) {
      final answers = puzzles[p].entries.map((e) => e.answer).toList();
      expect(answers.toSet().length, answers.length, reason: 'puzzle $p');
    }
  });

  test('the bank uses a real spread of answers', () {
    // A bank that leans on the same few convenient words would be dull
    // even though every individual grid is valid.
    final distinct = <String>{
      for (final puzzle in puzzles)
        for (final entry in puzzle.entries) entry.answer,
    };
    expect(distinct.length, greaterThan(300));
  });
}
